FROM apache/airflow:2.9.3

# USER root
# RUN apt-get update && apt-get install -y \
#     gcc \
#     g++ \
#     wget \
#     curl \
#     && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    pandas==2.1.4 \
    scikit-learn==1.3.2 \
    psycopg2-binary==2.9.9 \
    numpy \
    mlflow==2.11.3 \
    tenacity